{
  "hash": "0dd86eaa57d3fd10785a2e3c21292ac5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: |\n  <div class=\"tight-title\">\n    <div>ECOM30004/90004</div>\n    <div>Time Series Analysis and Forecasting</div>\n     <div class=\"spacer\"></div> <!-- blank line -->\n    <div class=\"bold\">Tutorial 6</div>\n\n    <div class=\"spacer\"></div> <!-- blank line -->\n\n    <div class=\"author\">Tutor: Pengyun (Kevin) Chen</div>\n    <div class=\"author\">University of Melbourne</div>\n    <div class=\"author\">Semester 2, 2025</div>\n  </div>\n\n  \nformat:\n  revealjs:\n    theme: simple\n    self-contained: false\n    chalkboard: true\n    width: 1220\n    height: 950\n    title-slide-attributes:\n      data-background-color: \"#094183\"\n    slide-number: true\n    center-title-slide: true\n    toc: false\n    css: styles.css\n    callout-appearance: simple\n    background-transition: fade\n    callout-icon: true\n    transition: slide\n    scrollable: true\n    code-block-height: 800px\n    code-line-numbers: true\n    mathjax: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js\"\n    html-math-method: mathjax\n    execute:\n      echo: true\n      eval: true\n      enabled: true\n---\n\n## Notice\n\n::: {.callout-warning title=\"Conditions of Use\"}\n\n- This document is intended for personal use and is NOT meant to be shared on the internet (e.g. Studocu, ThinkSwap, StudentVIP, Coursehero, etc.)\n- Do not share this document with anyone, even if they are enrolled in ECOM30004/90004.\n- Official course materials, such as lecture slides, tutorial sheets and prescribed readings should always be your primary point of reference.\n\n:::\n<div style=\"height: 0.2em;\"></div>\nSlides accessible here: ` \nhttps://pengyunc.quarto.pub/week6/`\n<myimage src=\"figures/QR.png\" width=\"30%\"></myimage>\n\n## This tutorial\n<blue>In this tutorial, we demonstrate forecasting the 2020Q1 CPI level, including stationarity tests, ARIMA model selection, and the final forecast computation.</blue>\n\n<div style=\"height: 0.2em;\"></div>\n:::{.callout-note title = \"Agenda\"}\n\n- <blue>Exercise 1(a):</blue> Transform CPI levels into log differences and select the ADF specification (lags).\n\n- <blue>Exercise 1(b):</blue> Test the log-differenced series for a unit root (ADF).\n\n- <blue>Exercise 1(c):</blue> Select the ARIMA model using AICc and Ljung–Box diagnostics.\n\n- <blue>Exercise 1(d):</blue> Forecast 2020Q1 inflation and the CPI level.\n\n- <blue>Exercise 2:</blue> Explain why first differencing removes a linear trend.\n:::\n\n<div style=\"height: 0.2em;\"></div>\n\n\n\n## We know that taking the logs is not enough... {auto-animate=\"true\"}\nRecall the unit root test results for log `CPI` from Self-directed Activities 5.\n\n::: {.cell}\n\n```{.r .cell-code}\ndt <- read.csv(\"CPI.csv\")\nY <- ts(log(dt$CPI), start = c(1922,2), end = c(2025,2), frequency=4)\nY <- window(Y, start = c(1946,1), end = c(2019,4))\n```\n:::\n\n\n<div class=\"horizontal-line\"></div>\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(Y)\n```\n\n::: {.cell-output-display}\n![](ECOM30004_Tutorial_6_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\nAn upward trend is obvious <blue>$\\to$ add a time trend in deterministic specification<blue>\n\n## We know that taking the logs is not enough... {auto-animate=\"true\"}\n:::{.callout-question}\nCarry out an ADF test of `Y`, present (i) the estimated test equation, \n(ii) the $t_{\\text{ADF}}$ test statistic, 5\\% critical value and decision, and (iii) its $p$-value.\n:::\n<div style=\"height: 0.5em;\"></div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(urca)    # For use of ur.df function\nadf <- ur.df(Y, type = \"trend\", selectlags = \"AIC\")\np_adf <- punitroot(adf@teststat[1], trend = \"ct\", statistic = \"t\")\n```\n:::\n\n<div style=\"height: 0.5em;\"></div>\n::: {.panel-tabset}\n\n## (i) test equation\nThe test equation is:\n$$\\Delta Y_{t}=\\beta_{0}+\\beta_{1}t+\\varphi Y_{t-1}+\\sum^{p-1}_{k=1}\\psi_{k} \\Delta Y_{t-k}+U_{t}$$\nThe hypotheses are:\n\\begin{align}\nH_{0}:&\\;\\varphi=0& &\\text{($Y_{t}$ has a unit root)}\\\\\nH_{1}:&\\;\\varphi<0& &\\text{($Y_{t}$ does not have a unit root)}\n\\end{align}\nThe number of lags of $\\Delta Y_{t}$ (i.e., $p-1$) is selected by an information criterion (AIC), where $p$ is the order of the underlying AR model.\n\n## (ii) test summary\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(adf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n############################################### \n# Augmented Dickey-Fuller Test Unit Root Test # \n############################################### \n\nTest regression trend \n\n\nCall:\nlm(formula = z.diff ~ z.lag.1 + 1 + tt + z.diff.lag)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.031901 -0.005565 -0.000645  0.004216  0.045287 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  8.657e-03  3.805e-03   2.275   0.0236 *  \nz.lag.1      2.743e-04  2.772e-03   0.099   0.9212    \ntt          -2.428e-05  3.733e-05  -0.651   0.5159    \nz.diff.lag   5.147e-01  5.049e-02  10.193   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.01025 on 290 degrees of freedom\nMultiple R-squared:  0.3263,\tAdjusted R-squared:  0.3193 \nF-statistic: 46.82 on 3 and 290 DF,  p-value: < 2.2e-16\n\n\nValue of test-statistic is: 0.099 16.8276 3.9857 \n\nCritical values for test statistics: \n      1pct  5pct 10pct\ntau3 -3.98 -3.42 -3.13\nphi2  6.15  4.71  4.05\nphi3  8.34  6.30  5.36\n```\n\n\n:::\n:::\n\n\n## (iii) $p$-value\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(p_adf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9973104\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.5em;\"></div>\nSince $p=0.997>0.05$, we <teal>**fail to reject** the null hypothesis $H_{0}$: there is unit root</teal>.\n<div style=\"height: 0.5em;\"></div>\n\n<blue>$\\implies$ Simply removing the trend component is not enough to make $Y_{t}$ stationary. </blue>\n\n<blue>$\\implies$ We need to take the first difference of log `CPI`.</blue>\n:::\n\n## Exercise 1(a)\n:::{.callout-question}\nNext create the first difference time series $\\Delta Y_{t}$ and a time series plot. Decide whether a trend is required for a unit root test for $\\Delta Y_{t}$. \n:::\n\n<div style=\"height: 0.5em;\"></div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDY <- diff(Y)   # DY is the log difference of the CPI -> Inflation\nplot(DY)\n```\n\n::: {.cell-output-display}\n![](ECOM30004_Tutorial_6_files/figure-revealjs/unnamed-chunk-6-1.png){width=960}\n:::\n:::\n\n<blue>**Observation:** There is no evidence of a linear trend in this time series.</blue> There are some extended periods (e.g. early 1950's and 1970-80's) when inflation was higher.\n\n## Exercise 1(b)  {auto-animate=\"true\"}\n:::{.callout-question}\nCarry out the unit root test on $\\Delta Y_{t}$. Conclude how many differences are required for log CPI to be stationary.\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadf <- ur.df(DY, type = \"drift\", selectlags = \"AIC\")\np_adf <- punitroot(adf@teststat[1], trend = \"c\", statistic = \"t\")\nsummary(adf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n############################################### \n# Augmented Dickey-Fuller Test Unit Root Test # \n############################################### \n\nTest regression drift \n\n\nCall:\nlm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.030300 -0.004863 -0.000533  0.003937  0.039013 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0031901  0.0008224   3.879  0.00013 ***\nz.lag.1     -0.2581651  0.0501006  -5.153 4.75e-07 ***\nz.diff.lag  -0.4253700  0.0530437  -8.019 2.64e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.009393 on 290 degrees of freedom\nMultiple R-squared:  0.3652,\tAdjusted R-squared:  0.3608 \nF-statistic: 83.41 on 2 and 290 DF,  p-value: < 2.2e-16\n\n\nValue of test-statistic is: -5.1529 13.2782 \n\nCritical values for test statistics: \n      1pct  5pct 10pct\ntau2 -3.44 -2.87 -2.57\nphi1  6.47  4.61  3.79\n```\n\n\n:::\n:::\n\n<div class=\"horizontal-line\"></div>\nThe estimated ADF test equation is:\n\n$$\\widehat{\\Delta(\\Delta Y_{t})}=0.0031-0.258\\Delta Y_{t-1}-0.4253\\Delta(\\Delta Y_{t-1})$$\n\n## Exercise 1(b)  {auto-animate=\"true\"}\n:::{.callout-question}\nCarry out the unit root test on $\\Delta Y_{t}$. Conclude how many differences are required for log CPI to be stationary.\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadf <- ur.df(DY, type = \"drift\", selectlags = \"AIC\")\np_adf <- punitroot(adf@teststat[1], trend = \"c\", statistic = \"t\")\nsummary(adf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n############################################### \n# Augmented Dickey-Fuller Test Unit Root Test # \n############################################### \n\nTest regression drift \n\n\nCall:\nlm(formula = z.diff ~ z.lag.1 + 1 + z.diff.lag)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.030300 -0.004863 -0.000533  0.003937  0.039013 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  0.0031901  0.0008224   3.879  0.00013 ***\nz.lag.1     -0.2581651  0.0501006  -5.153 4.75e-07 ***\nz.diff.lag  -0.4253700  0.0530437  -8.019 2.64e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.009393 on 290 degrees of freedom\nMultiple R-squared:  0.3652,\tAdjusted R-squared:  0.3608 \nF-statistic: 83.41 on 2 and 290 DF,  p-value: < 2.2e-16\n\n\nValue of test-statistic is: -5.1529 13.2782 \n\nCritical values for test statistics: \n      1pct  5pct 10pct\ntau2 -3.44 -2.87 -2.57\nphi1  6.47  4.61  3.79\n```\n\n\n:::\n:::\n\n<div class=\"horizontal-line\"></div>\nThe $t$-statistic is $-5.1529$, and the $5\\%$ critical value is $-2.87$.\n\n<blue>Since $-5.1539<-2.87$, we **reject** $H_0$: $\\Delta Y_{t}$ has a unit root.</blue>\n\n\n## Exercise 1(b)  {auto-animate=\"true\"}\n:::{.callout-question}\nCarry out the unit root test on $\\Delta Y_{t}$. Conclude how many differences are required for log CPI to be stationary.\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nadf <- ur.df(DY, type = \"drift\", selectlags = \"AIC\")\np_adf <- punitroot(adf@teststat[1], trend = \"c\", statistic = \"t\")\nsummary(adf)\n```\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\nThe $t$-statistic is $-5.1529$, and the $5\\%$ critical value is $-2.87$.\n\nSince $-5.1539<-2.87$, we **reject** $H_0$: $\\Delta Y_{t}$ has a unit root.\n\n::: {.fragment}\n<div class=\"horizontal-line\"></div>\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(p_adf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.828593e-06\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.5em;\"></div>\n<teal>Alternatively, since $p=9.82\\times 10^{-6}<0.05$, we **reject $H_0$: $\\Delta Y_{t}$ has a unit root**.</teal>\n:::\n\n:::{.fragment}\n<div class=\"horizontal-line\"></div>\n<blue>**Conclusion:** To render log CPI stationary, it is necessary to difference the series *once*.</blue>\n:::\n\n\n## Exercise 1(c)  {auto-animate=\"true\"}\n:::{.callout-question}\nSpecify and estimate an appropriate ARIMA($p,d,q$) model for $Y_{t}$.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-tip}\n- Since first differencing is required for log CPI to be stationary, we need $d=1$.\n- How to select $(p,q)$? <green>$\\to$ Conduct a grid search for $p=0,\\dots,4$ and $q=0,\\dots,4$</green>\n:::\n\n<div class=\"horizontal-line\"></div>\n:::{.callout-note title=\"Code Structure\"}\n- Set up container matrices for AICc values (`AICc`) and Ljung-Box test $p$-values (`LBp`)\n\n- For each $(p,q)$ combination:\n  - Fit the ARIMA($p,1,q$) model with `Arima()` function, and extract AICc\n  \n  - Extract the Ljung-Box $p$-values with `checkresiduals()` function\n  \n- Choose the model with the **lowest** AICc, and verify that its <teal>Ljung-Box $H_{0}$ (no autocorrelation)</teal> is not rejected.\n\n:::\n\n\n## Exercise 1(c)  {auto-animate=\"true\"}\n:::{.callout-question}\nSpecify and estimate an appropriate ARIMA($p,d,q$) model for $Y_{t}$.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-tip}\n- Since first differencing is required for log CPI to be stationary, we need $d=1$.\n- How to select $(p,q)$? <green>$\\to$ Conduct a grid search for $p=0,\\dots,4$ and $q=0,\\dots,4$</green>\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(forecast)\n\npmax <- 4\nqmax <- 4\nLBp <- matrix(nrow=pmax+1, ncol=qmax+1)\nrownames(LBp) <- paste0(\"p=\", 0:pmax)\ncolnames(LBp) <- paste0(\"q=\", 0:qmax)\nAICc <- LBp\n\nfor (p in 0:pmax){\n  for (q in 0:qmax){\n    eq <- Arima(DY, order=c(p,0,q))\n    capture.output(LBp[p+1,q+1] <- checkresiduals(eq,\n      plot=FALSE)$p.value)\n    AICc[p+1,q+1] <- eq$aicc\n  }  \n}\n```\n:::\n\n\n\n## Exercise 1(c)  {auto-animate=\"true\"}\n:::{.callout-question}\nSpecify and estimate an appropriate ARIMA($p,d,q$) model for $Y_{t}$.\n:::\n<div style=\"height: 0.5em;\"></div>\n\nResidual autocorrelation result (`=0` if $H_{0}$ maintained)\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(1*(LBp<0.05))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    q=0 q=1 q=2 q=3 q=4\np=0   1   1   1   1   1\np=1   1   1   0   0   0\np=2   1   1   0   0   0\np=3   1   1   0   0   0\np=4   1   1   0   0   0\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\nModel to minimise AICc:\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(AICc==min(AICc))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      q=0   q=1   q=2   q=3   q=4\np=0 FALSE FALSE FALSE FALSE FALSE\np=1 FALSE FALSE FALSE  TRUE FALSE\np=2 FALSE FALSE FALSE FALSE FALSE\np=3 FALSE FALSE FALSE FALSE FALSE\np=4 FALSE FALSE FALSE FALSE FALSE\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.5em;\"></div>\n\n:::{.fragment}\n\n<blue>**Conclusion:** The chosen model is ARIMA($1,1,3$) for $Y_{t}$.</blue>\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\n<blue>Use the chosen model to calculate a forecast of inflation</blue> and the CPI for the March quarter of 2020.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-tip}\nNote that we have selected ARMA(1,3) for $\\Delta Y_{t}\\equiv \\Delta\\log(CPI_{t})$ in Exercise 1(c).\n:::\n\n:::{.fragment}\n<div style=\"height: 0.1em;\"></div>\nForecast 2020Q1 inflation:  $\\Delta{}Y_{2020Q1}=\\log(CPI_{2020Q1})-\\log(CPI_{2019Q4})$\n\n::: {.cell}\n\n```{.r .cell-code}\neq <- Arima(DY, order = c(1,0,3))\nForecastInflation_2020q1 <- forecast(eq, h=1)$mean\nprint(ForecastInflation_2020q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Qtr1\n2020 0.00710347\n```\n\n\n:::\n:::\n\n:::\n\n:::{.fragment}\n<div class=\"horizontal-line\"></div>\n**The inflation forecast is based on an approximation…**\n\nRecall from Week 1 tutorial that for small $r$ values, $\\log(1+r)\\approx r$:\n\\begin{align}\nCPI_{2019Q4}(1+\\text{inflation}_{2020Q1})&=CPI_{2020Q1}\\\\\n\\log(1+\\text{inflation}_{2020Q1})&=\\log(CPI_{2020Q1})-\\log(CPI_{2019Q4})\\\\\n\\implies\\qquad \\color{blue}{\\text{inflation}_{2020Q1}}&\\approx\\log(CPI_{2020Q1})-\\log(CPI_{2019Q4})\n\\end{align}\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-tip}\nNote that we have selected ARMA(1,3) for $\\Delta Y_{t}\\equiv \\Delta\\log(CPI_{t})$ in Exercise 1(c).\n:::\n<div style=\"height: 0.1em;\"></div>\n**How can we forecast the 2020Q1 CPI?**\n\nWe know that\n\\begin{align}\n\\color{blue}{\\text{inflation}_{2020Q1}}&\\approx\\log(CPI_{2020Q1})-\\log(CPI_{2019Q4})\n\\end{align}\n\n:::{.fragment}\nthus we have $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times(1+\\widehat{\\operatorname{inflation}}_{2020Q1})$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a ts of CPI (i.e. not log CPI)\nCPI <- ts(dt$CPI, start=c(1922,2), end=c(2025,2), frequency=4)\nCPI_2019q4 <- CPI[which(time(CPI)==2019.75)]\n\n# Forecast CPI for 2020q1\nForecastCPI_2020q1 <- CPI_2019q4*(1+ForecastInflation_2020q1)\nprint(ForecastCPI_2020q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 117.0254\n```\n\n\n:::\n:::\n\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n\n**How can we forecast the 2020Q1 CPI?**\n\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times(1+\\widehat{\\operatorname{inflation}}_{2020Q1})$\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 117.0254\n```\n\n\n:::\n:::\n\n<div class=\"horizontal-line\"></div>\n\n:::{.fragment}\n<blue>Second approach:</blue>\n\n- Since we know that <blue>$\\widehat{\\log(CPI_{2020Q1})}=\\log(CPI_{2019Q4})+\\widehat{\\text{inflation}}_{2020Q1}$</blue>\n- then we can just take the exponential of the logs:\n<blue>$$\\widehat{CPI_{2020Q1}}=\\exp(\\widehat{\\log(CPI_{2020Q1})})=\\exp(\\log(CPI_{2019Q4})+\\widehat{\\text{inflation}}_{2020Q1})$$</blue>\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n**How can we forecast the 2020Q1 CPI?**\n\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times(1+\\widehat{\\operatorname{inflation}}_{2020Q1})$\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 117.0254\n```\n\n\n:::\n:::\n\n<div class=\"horizontal-line\"></div>\n\n<blue>Second approach: $\\widehat{CPI_{2020Q1}}=\\exp(\\log(CPI_{2019Q4})+\\widehat{\\text{inflation}}_{2020Q1})$</blue>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(Y)\nForecastY_2020Q1 <- Y[n] + ForecastInflation_2020q1\nprint(ForecastY_2020Q1)      # Forecasted log CPI at 2020Q1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 4.762416\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.3em;\"></div>\n\n::: {.cell}\n\n```{.r .cell-code}\nForecastCPI_2020q1 <- exp(ForecastY_2020Q1)\nprint(ForecastCPI_2020q1)    # Forecasted CPI level at 2020Q1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 117.0284\n```\n\n\n:::\n:::\n\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n\n:::{.callout-tip}\nRecall that we modeled $\\Delta Y_{t}$ as ARMA(1,3) <green>$\\Rightarrow$ $Y_{t}$ should be modeled as ARMA(1,1,3)</green>.\n:::\n\n::: {.panel-tabset}\n\n## ARIMA(1,1,3) for $Y_{t}\\equiv\\log(CPI_{t})$\n\n\n::: {.cell}\n\n```{.r .cell-code}\neq1 = Arima(Y, order = c(1,1,3), xreg = (1:n))\nprint(eq1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: Y \nRegression with ARIMA(1,1,3) errors \n\nCoefficients:\n         ar1      ma1     ma2     ma3    xreg\n      0.8316  -0.6377  0.2380  0.1276  0.0120\ns.e.  0.0501   0.0701  0.0629  0.0679  0.0022\n\nsigma^2 = 8.245e-05:  log likelihood = 970.4\nAIC=-1928.81   AICc=-1928.52   BIC=-1906.69\n```\n\n\n:::\n:::\n\n<div style=\"height: 0.1em;\"></div>\n$\\displaystyle\\textsf{The model is:}\\quad\\boxed{\\quad\\begin{aligned}\n\\color{blue}{Y_{t}}\\,&\\color{blue}{=\\beta_{1}t+Z_{t}}\\\\\n\\Delta Z_{t}&=\\phi_{1}\\Delta Z_{t-1}+U_{t}+\\theta_{1}U_{t-1}+\\theta_{2}U_{t-2}+\\theta_{3}U_{t-3}\n\\end{aligned}\\quad}$\n\n::: {.absolute top=\"530px\" left=\"820px\" style=\"font-size: 36px;\"}\n<blue>These are two versions of the same model and give equivalent coefficient estimates!</blue>\n:::\n\n\n\n## ARMA(1,3) for $\\Delta Y_{t}\\equiv\\Delta \\log(CPI_{t})$\n\n::: {.cell}\n\n```{.r .cell-code}\neq = Arima(DY, order = c(1,0,3))\nprint(eq)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSeries: DY \nARIMA(1,0,3) with non-zero mean \n\nCoefficients:\n         ar1      ma1     ma2     ma3    mean\n      0.8316  -0.6377  0.2380  0.1276  0.0120\ns.e.  0.0501   0.0701  0.0629  0.0679  0.0022\n\nsigma^2 = 8.244e-05:  log likelihood = 970.4\nAIC=-1928.81   AICc=-1928.52   BIC=-1906.69\n```\n\n\n:::\n:::\n\n$\\displaystyle\\textsf{The model is:}\\quad\\boxed{\\quad\\begin{aligned}\n\\color{blue}{\\Delta Y_{t}}\\,&\\color{blue}{=\\beta_{1}+\\Delta Z_{t}}\\\\\n\\Delta Z_{t}&=\\phi_{1}\\Delta Z_{t-1}+U_{t}+\\theta_{1}U_{t-1}+\\theta_{2}U_{t-2}+\\theta_{3}U_{t-3}\n\\end{aligned}\\quad}$\n:::\n\n::: {.absolute top=\"530px\" left=\"820px\" style=\"font-size: 36px;\"}\n<blue>These are two versions of the same model and give equivalent coefficient estimates!</blue>\n:::\n\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n\n:::{.callout-tip}\nRecall that we modeled $\\Delta Y_{t}$ as ARMA(1,3) <green>$\\Rightarrow$ $Y_{t}$ should be modeled as ARMA(1,1,3)</green>.\n:::\n<div style=\"height: 0.1em;\"></div>\nWe can forecast $Y_{2020Q1}\\equiv\\log(CPI_{2020Q1})$ with <purple>ARMA(1,3) of $\\Delta Y_{t}$ with drift</purple>:\n\n\n::: {.cell}\n\n```{.r .cell-code}\neq = Arima(DY, order = c(1,0,3))\nForecastInflation_2020q1 <- forecast(eq, h=1)$mean\nn <- length(Y)\nForecastY_2020Q1 <- Y[n] + ForecastInflation_2020q1\nprint(ForecastY_2020Q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 4.762416\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n<div style=\"height: 0.8em;\"></div>\nWe can also forecast $Y_{2020Q1}$ with <teal>ARIMA(1,1,3) of $Y_{t}$ with drift and trend</teal>:\n\n::: {.cell}\n\n```{.r .cell-code}\neq1 = Arima(Y, order = c(1,1,3), xreg = (1:n))\nForecastY_2020q1 <- forecast(eq1, xreg=(n+1))$mean\nprint(ForecastY_2020q1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         Qtr1\n2020 4.762416\n```\n\n\n:::\n:::\n\n:::\n\n:::{.fragment}\n\n::: {.absolute top=\"548px\" left=\"250px\" style=\"font-size: 36px;\"}\n<blue>$\\to\\;\\;\\boxed{\\;\\textsf{Using either model is fine.}\\;}$</blue>\n:::\n\n::: {.absolute top=\"833px\" left=\"250px\" style=\"font-size: 36px;\"}\n<blue>$\\to\\;\\;\\boxed{\\;\\textsf{Using either model is fine.}\\;}$</blue>\n:::\n\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n**Remarks on the CPI forecasts:** \n\nBoth approaches are approximations.\n\n:::{.fragment}\n<div class=\"horizontal-line\"></div>\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times (1+\\color{purple}{\\underbrace{\\widehat{\\text{inflation}}_{2020Q1}}_{\\text{approximation}}})$\n:::\n\n:::{.fragment}\n<div class=\"horizontal-line\"></div>\nSecond approach: $\\widehat{CPI}_{2020Q1}=\\exp(\\log(\\widehat{CPI}_{2020Q1}))$\n:::\n\n\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n**Remarks on the CPI forecasts:** \n\nBoth approaches are approximations.\n\n\n<div class=\"horizontal-line\"></div>\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times (1+\\color{purple}{\\underbrace{\\widehat{\\text{inflation}}_{2020Q1}}_{\\text{approximation}}})$\n\n\n<div class=\"horizontal-line\"></div>\nSecond approach: $\\widehat{CPI}_{2020Q1}=\\exp(\\color{teal}{\\log(\\widehat{CPI}_{2020Q1})}\\color{black}{)}$\n\n<teal>\n<div style=\"height: 0.1em;\"></div>\nThe inner part is an estimate of an expectation conditional on information set $\\mathcal{Y}_{2019Q4}$:\n$$\\widehat{\\log(CPI_{2020Q1})}\\equiv\\hat{Y}_{2020Q1}=\\hat{\\mathbb{E}}[Y_{2020Q1}\\mid \\mathcal{Y}_{2019Q4}]$$\n</teal>\n\n:::{.fragment}\n$$\\implies \\widehat{\\log(CPI_{2020Q1})}=\\hat{\\mathbb{E}}[\\log(CPI_{2020Q1})\\mid \\mathcal{Y}_{2019Q4}]$$\nand this is estimated through the ARIMA(1,1,3) model fitted on $Y_{t}$.\n:::\n\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n**Remarks on the CPI forecasts:** \n\nBoth approaches are approximations.\n\n\n<div class=\"horizontal-line\"></div>\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times (1+\\color{purple}{\\underbrace{\\widehat{\\text{inflation}}_{2020Q1}}_{\\text{approximation}}})$\n\n\n<div class=\"horizontal-line\"></div>\nSecond approach: $\\widehat{CPI}_{2020Q1}=\\exp(\\color{blue}{\\hat{\\mathbb{E}}[\\log(CPI_{2020Q1})\\mid\\mathcal{Y}_{2019Q4}]}\\color{black}{)}$\n<div style=\"height: 0.5em;\"></div>\n<oblue>\n**Question:** Does the following hold?\n$$\\color{blue}{\\mathbb{E}[{CPI}_{2020Q1}\\mid\\mathcal{Y}_{2019Q4}]\\overset{?}{=}\\exp(\\mathbb{E}[\\log(CPI_{2020Q1})\\mid \\mathcal{Y}_{2019Q4}])}$$\n</oblue>\n\n\n:::{.fragment}\n<blue>\n**Answer:** No. This is because of Jensen's inequality - since $\\exp(x)$ is convex:\n$$\\mathbb{E}[\\exp(\\log(CPI_{2020Q1})\\mid \\mathcal{Y}_{2019Q4})]>\\exp(\\mathbb{E}[\\log(CPI_{2020Q1})\\mid \\mathcal{Y}_{2019Q4}])$$\n</blue>\n:::\n\n\n## Exercise 1(d)  {auto-animate=\"true\"}\n:::{.callout-question}\nUse the chosen model to calculate a forecast of inflation and <blue>the CPI for the March quarter of 2020</blue>.\n:::\n<div style=\"height: 0.5em;\"></div>\n**Remarks on the CPI forecasts:** \n\nBoth approaches are approximations.\n\n\n<div class=\"horizontal-line\"></div>\nFirst approach: $\\widehat{CPI}_{2020Q1}=CPI_{2019Q4}\\times (1+\\color{purple}{\\underbrace{\\widehat{\\text{inflation}}_{2020Q1}}_{\\text{approximation}}})$\n\n\n<div class=\"horizontal-line\"></div>\nSecond approach: $\\widehat{CPI}_{2020Q1}=\\exp(\\hat{\\mathbb{E}}[\\log(CPI_{2020Q1})\\mid\\mathcal{Y}_{2019Q4}]\\color{black}{)}$\n<div style=\"height: 0.5em;\"></div>\n<blue>\nThus this estimator is actually biased for the conditional mean  $\\mathbb{E}[CPI_{2020Q1}\\mid\\mathcal{Y}_{2019Q4}]$:\n$$\\mathbb{E}[CPI_{2020Q1}\\mid\\mathcal{Y}_{2019Q4}]>\\exp(\\mathbb{E}[\\log(CPI_{2020Q1})\\mid \\mathcal{Y}_{2019Q4}])$$\n</blue>\n\n:::{.fragment}\n<green>\nNevertheless, in practice, simply taking the exponential tends to work well in providing a good approximation.\n</green>\n:::\n\n## Exercise 2  {auto-animate=\"true\"}\n:::{.callout-question}\nIt seems like if $Y_{t}$ has a linear trend then $\\Delta Y_{t}$ does not. Explain why this is.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-note}\n<blue>Recall from Exercise 1(d):</blue> ARIMA(1,1,3) with trend on $Y_{t}$ produced the same parameter estimates as ARMA(1,3) with drift on $\\Delta Y_{t}$. Why is that?\n:::\n<div style=\"height: 0.5em;\"></div>\n\n:::{.fragment}\nThe `Arima` function is estimating the following set of equations:\n<div style=\"height: 0.5em;\"></div>\n:::\n\n::: {.incremental}\n- ARIMA(1,1,3) with drift and trend for $Y_{t}$:\n\\begin{align*}\nY_{t}&= \\beta_{0}+\\beta_{1}t+Z_{t}\\\\\n\\Delta Z_{t}&=\\phi_{1}\\Delta Z_{t-1}+U_{t}+\\theta_{t} U_{t-1}+\\theta_{2}U_{t-2}+\\theta_{3}U_{t-3}\n\\end{align*}<div style=\"height: 0.5em;\"></div>\n\n- ARMA(1,3) with drift for $\\Delta Y_{t}$:\n\\begin{align*}\n\\Delta Y_{t}&= \\alpha+W_{t}\\\\\nW_{t}&=\\phi_{1}W_{t-1}+U_{t}+\\theta_{t} U_{t-1}+\\theta_{2}U_{t-2}+\\theta_{3}U_{t-3}\n\\end{align*}\n\n:::\n\n:::{.fragment}\nIf both gives the exact same estimates, then $\\alpha=\\beta_{1}$ and $W_{t}=\\Delta Z_{t}$.\n:::\n\n\n## Exercise 2 {auto-animate=\"true\"}\n:::{.callout-question}\nIt seems like if $Y_{t}$ has a linear trend then $\\Delta Y_{t}$ does not. Explain why this is.\n:::\n<div style=\"height: 0.5em;\"></div>\n:::{.callout-note}\n<blue>Show that $\\alpha=\\beta_{1}$, $W_{t}=\\Delta Z_{t}$ in the following equations:</blue>\n\n$$Y_{t}=\\beta_{0}+\\beta_{1}t+Z_{t}\\qquad\\qquad\\Delta Y_{t}=\\alpha+W_{t}$$\n:::\n<div style=\"height: 0.5em;\"></div>\n\n:::{.fragment}\nSubtract $Y_{t-1}$ on both sides gives:\n\n$$Y_{t}\\,\\color{blue}{-\\,Y_{t-1}}\\color{black}{\\,=(\\beta_{0}+\\beta_{1}t+Z_{t})}\\color{blue}{\\,-\\,(\\beta_{0}+\\beta_{1}(t-1)+Z_{t-1})}$$\n:::\n\n:::{.fragment}\nThen simplify:\n\\begin{align*}\n\nY_{t}-Y_{t-1}&=\\beta_{0}-\\beta_{0}+\\beta_{1}(t-(t-1))+Z_{t}-Z_{t-1}\\\\\n\\Delta Y_{t}&=\\beta_{1}+\\Delta Z_{t}\n\\end{align*}\n:::\n\n:::{.fragment}\nWe have thereby shown that $\\alpha=\\beta_{1}$ and $W_{t}=\\Delta Z_{t}$.\n<div style=\"height: 0.5em;\"></div>\n:::\n\n:::{.fragment}\n<blue>In addition, we have shown that taking the first difference removes the linear trend.</blue>\n<blue>\n$$Y_{t}=\\beta_{0}+\\beta_{1}t+Z_{t}\\quad\\xrightarrow{\\;\\textsf{take first difference}\\;}\\quad \\Delta Y_{t}=\\beta_{1}+\\Delta Z_{t}$$\n</blue>\n:::\n\n\n## {data-background-color=\"#094183\"}\n<div style=\"height: 85vh; display: flex; align-items: center; justify-content: center; color: white; font-size: 2em;\">\nThank you for coming!\n</div>\n\n\n<script>\ndocument.querySelectorAll(\"myimage\").forEach(el => {\n  const src = el.getAttribute(\"src\");\n  const width = el.getAttribute(\"width\") || \"100%\";\n\n  const img = document.createElement(\"img\");\n  img.src = src;\n  img.style.width = width;\n  img.style.maxWidth = \"100%\";  // prevent overflow\n  el.style.display = \"block\";\n  el.style.textAlign = \"center\";\n  \n  el.appendChild(img);\n});\n</script>",
    "supporting": [
      "ECOM30004_Tutorial_6_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}